# Planner selection
# base_global_planner: "navfn/NavfnROS"
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
# base_local_planner: "eband_local_planner/EBandPlannerROS"
# base_local_planner: "teb_local_planner/TebLocalPlannerROS"

# Recovery behaviors are defined in robot folders

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.1
planner_patience: 5.0

NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.0
  use_dijkstra: true
  # debug
  visualize_potential: true

# Local planner
controller_frequency: 10.0
controller_patience: 15.0

TrajectoryPlannerROS:
  # tolerances (defaults)
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false
  # base vel/accel profile is in robot folders
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.5
  max_vel_x: 0.75
  min_vel_x: 0.2
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 2.5
  min_vel_theta: -2.5
  min_in_place_vel_theta: 2.0
  holonomic_robot: false
  # forward simulation
  sim_time: 2.5
  sim_granularity: 0.25
  angular_sim_granularity: 0.05
  vx_samples: 12
  vtheta_samples: 25
  # scoring (defaults)
  meter_scoring: true
  pdist_scale: 0.5
  gdist_scale: 5.0
  occdist_scale: 0.1
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: true
  dwa: true
  # other
  oscillation_reset_dist: 0.05
  # debug
  publish_cost_grid_pc: false

EBandPlannerROS:
  # tolerances
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
  # velocity limits
  max_vel_lin: 0.75
  max_vel_th: 0.7
  min_vel_lin: 0.1
  min_vel_th: 0.0
  min_in_place_vel_theta: 0.55
  in_place_trans_vel: 0.0
  # acceleration limits
  max_acceleration: 0.5
  max_translational_acceleration: 0.5
  max_rotational_acceleration: 1.5
  differential_drive: true
  # eband specific parameters
  # virtual_mass: 0.1
  k_prop: 1.0
  k_damp: 5.0
  eband_min_relative_overlap: 0.7
  eband_internal_force_gain: 0.1
  eband_external_force_gain: 2.0
  costmap_weight: 15.0
  bubble_velocity_multiplier: 2.0
  rotation_threshold_multiplier: 1.0
  rotation_correction_threshold: 0.5

TebLocalPlannerROS:
  # tolerances
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  free_goal_vel: false
  # velocity and acceleration limits
  acc_lim_x: 0.5
  acc_lim_theta: 1.5
  max_vel_x: 0.75
  max_vel_x_backwards: 0.001
  max_vel_theta: 0.7
  # robot definition
  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: false
  footprint_model:
    type: "point"
    radius: 0.3
  # costmap details
  min_obstacle_dist: 0.8
  costmap_obstacles_behind_robot_dist: 0.5
  inflation_dist: 0.9
  # optimization parameters
  no_inner_iterations: 5
  no_outer_iterations: 2
  penalty_epsilon: 0.0
  weight_max_vel_x: 1.0
  weight_max_vel_theta: 2.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_forward_drive: 5.0
